version: "3.5"

services:
  app:
    # image: 'jc21/nginx-proxy-manager:2.9.0'
    # Sorry for the esoteric fuckery. but this PR has *.domain.bla fix in it.
    image: 'jc21/nginx-proxy-manager:github-pr-1181' 
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    restart: always 
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
  db:
    image: 'jc21/mariadb-aria:10.4'
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

  assistant:
    build: .
    restart: always 
    depends_on:
      - app
    entrypoint: "npm run dev"
    environment:
      username: 'info@xantios.nl' # your npm login
      password: 'xaphn42X' # npm password
      le_email: 'letsencrypt@xantios.nl'
    volumes:
      - ./app:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

